# Generated by Django 6.1.1 on 2026-09-30 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('road', 'Road'), ('electricity', 'Electricity'), ('water', 'Water'), ('waste', 'Waste Management'), ('security', 'Security'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('other', 'Other')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='issues/')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('review', 'Under Review'), ('progress', 'In Progress'), ('resolved', 'Resolved')], default='reported', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
